language: objective-c
osx_image: xcode8.3
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script:
- ./build.sh SwiftyJSON/SwiftyJSON
deploy:
  provider: releases
  api_key:
    secure: ncvTqhIqEIYxzRVVZKk58PPXhlRGgbLfIsj/NS+25dLyU02kUu49CsXxTxYfT1+AEqzwzbXVtBIwz5S0TjWwrlxZexjwwG7tC+Mr7VvhKv89mRbDn0iuCFJPitLV+VL2nkc7dcLSL2Ui35Tt24hx9/+EZ5n1+Xr7YQJaJB9nUp7i1wWC+vysedvDv82CqrAiqpsLKOeV8x9d8n+Nx5X5ON7566se6+Z7AY2eFxVtoXM40sUOSyebvfGDVEFG3wkkgbvlccyq4TVUZdU1BcKzyjiTJs56aINZIZd2r2FBEWcdpafsPh4Ig6vu0FrHTv49PgyWy90nDdraAx7trArgkIzlUKSkImZD+G4L0CIwH759vqBaRXkHUZyMGINvuT4KNUgzptY2DFJ5b0bmHqmqMeIo/Yol/vaZBcP46kVz7V0uI0APJXM1jjGFWRtxDSANBTEDn0rRJdzOGN7nYX6J8O28R9d4NHc5Rtv94ORN1Ldv9lw2e3RVvc/cT0cEQPIGAdkIWIc3NpVipHEkV5yp9wUZKtuNsMc4b0ZXpqqcIeH/EPHTTgbi2f9moBZF5juEBomQm51PT/9mzgET3vfv4Ng1WZ5OhClPppaw7W+uR1pUeI/GVnBKSN5Vu3UwMzW9AvBhShynme7QKMZY6qQHWGyw0iWs0hqz6U9hzJs9JIE=
  file_glob: true
  file: Archives/*
  skip_cleanup: true
  on:
    tags: true
