language: objective-c
osx_image: xcode8.3
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script:
- ./build.sh SwiftyJSON/SwiftyJSON
deploy:
  provider: releases
  api_key:
    secure: bXKS2XG6JCuGKu0ELjKOgxRubWegBURtHooYcFu38SER/RjrxmvHHwfi0Q1KwPKuTdb2dr9H1ytQ2G0TK7JmaOfdFn4hCfG6G9nnktS/DNp0gnxUXmfcBnAmYwhRKz7vbUrkwJhwqL6oiBmy4k2f/tKcYIkttc61K9/lHIYutwnJwRRDwfukN1dF+4cFgdNNKTf5O7Iagm9h/UqTzmpmrxBr2O+EDTPbTGR4IP52QkBA3xe061CynySA59JtRtVN6EjzDOf+zOox6Lowe26qDudHWFg3tjJ7ny1JhecXCzkS5vzmDnLpaDy2CI1qOwGxFNpXawQDVE2D87Dtxu1RCYXtdunPhW0jKm/6mhHUxfYvmlk4VuBIKc+XOitZyEs8CnG8R0B1QmY9bwnqdeSt7feCuoLqgXYX19ayukzAw+25U1sG9PjKHthylXFu1hA2DrgXKqKFgUaT7L1U+Oq5AURKLPM3GrDWM0Drv5oEjgKavx8A4kAZzrVkwwwXU8TphW5sITsYJEfPzpa9hHbAbS+E2KwcLo8rqtQOk6E0/5I0YYmPmtuaZtwDuPoD5ymQA+O36mAIx+bH6ikEWlAW7LOzmKgz2S5WozAOeGpkSKl1PS8b8cqttAITCi6yMuFl9adZ7RHRqG0VfDnoSl6JztgCQbj5CR9nqhItbQU+JuQ=
  file_glob: true
  file: Archives/*
  skip_cleanup: true
  on:
    tags: true
