language: objective-c
osx_image: xcode8.3
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script:
- ./build.sh SwiftyJSON/SwiftyJSON
deploy:
  provider: releases
  api_key:
    secure: bCAZb3o3JgKVCgIQ/k240TCsT9e9tBnxHLV9QBq5hAfZTIbF0XsR2Zz6I8XEk8cfYa5zLUIuDsbNX3olEm1XoFsHB20i7xC7La3A+kamaHbCrPeaUj2jhdIkZiqMZDhkx8dqPwZaBxC3tQzqBzDhiKhC+uUtz2VkBI6SRVGm3HkpbPCU6DVPIa16AZTfTJhPcV88tarbSj1bfIQgZdBbS9+aXz4PxAMRQJy9W00dIyTheWb3TluvMn33tuBgxpqOautR4x7HBdnRbkFCzBE4GbSkJeZMdIZjFnumEA1XqYJQToulYwWEtXqrA1a8PnKvlJWOQOfDNUKwyeZVh+EdNEZ8DKBjZ67OK2XPrzlnZJmNeLBf43FCRE3slqkmfqObK9iWEHQKQSAfgwO9D2raza2u06g/z9QZn09oJfBwYMsY3uHHY6y+H+JqmhTI2m/Pl7XTOHaEerkKw1qovsSg4yN1f/CdJfpoPfaMjD1f1SM3zJM4v6VYpR6FnJhXxcnonS3IjqKHXTafVq8ALxvFMo0GFVlpWlprY4mfoTcSb/4EiE4292f3u/ETeQhdKF1UKjDZKDL8pCwNSIYDene1kWecMCCnhUoJADeiOXLtHz3jNoJgWcfHr18Gy3ktkKRE0pTS8ZkEMeLx5ppWcDVvrk5jHOThcDE+fJZ2neO/72Q=
  file_glob: true
  file: Archives/*
  skip_cleanup: true
  on:
    tags: true
